services:
  - type: web
    name: repolens
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: GITHUB_TOKEN
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: AI_PROVIDER
        value: groq
      - key: GROQ_MODEL
        value: llama3-70b-8192
      - key: CORS_ORIGINS
        value: https://repolens.onrender.com
      - key: REPO_STORAGE_PATH
        value: /data/repos
      - key: LOG_LEVEL
        value: INFO
    disk:
      name: repolens-data
      mountPath: /data
      sizeGB: 1
